# Generated by Django 5.0 on 2024-01-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0003_cartdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='TotalPice',
            new_name='TotalPrice',
        ),
    ]
