# Generated by Django 5.0 on 2024-01-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0004_rename_totalpice_cartdb_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='TotalPrice',
            new_name='TotalPice',
        ),
    ]
